apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: technological-snipe-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/technological-snipe-dotnet-basic-gitops